[package]
name = "raw_player"
version = "2026.2.0-canary.1"
edition = "2024"
rust-version = "1.88"
description = "Raw audio/video player for Rust"
readme = "README.md"
homepage = "https://github.com/shiguredo/raw-player-rs"
repository = "https://github.com/shiguredo/raw-player-rs"
license = "Apache-2.0"
build = "build.rs"
include = ["/LICENSE", "/README.md", "/build.rs", "/src/**"]

# 以降は外部ライブラリビルド用のメタデータ
# (この内容は build.rs の中からのみ参照される)
[package.metadata.external-dependencies.sdl3]
url = "https://github.com/libsdl-org/SDL"
tag = "release-3.4.12"

[workspace]
members = ["pbt"]

[dependencies]

[dev-dependencies]
shiguredo_audio_device = "=2026.2.0-canary.1"
shiguredo_video_device = "=2026.2.0-canary.2"

[build-dependencies]
bindgen = "0.72"
shiguredo_cmake = "4.4"
shiguredo_toml = "2026.2"

[features]
source-build = []
